% Example state matrix: Single state; one second pause

sma = NewStateMachine;

sma = AddState(sma, 'Name', 'MyState', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {'Valve', 1, 'PWM1', 16, 'PWM2', 255});