% Example state matrix: Sends code '1' to trigger the PsychToolbox sound server

sma = NewStateMatrix();

sma = AddState(sma, 'Name', 'Delay', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', 'TriggerSound'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'TriggerSound', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {'BNCState', 1, 'SoftCode', 1});

% Set soft code handler to send byte 
BpodSystem.SoftCodeHandlerFunction = 'SoftCodeSoundServer_CodeHandler';