% Example state matrix: Trigger the sound server on Port1in

sma = NewStateMatrix();
sma = AddState(sma, 'Name', 'WaitForPoke', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port1In', 'TriggerSound1', 'Port2In', 'TriggerSound2', 'Port3In', 'TriggerSound3'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'TriggerSound1', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'Delay'},...
    'OutputActions', {'Serial1Code', 1, 'BNCState', 2});
sma = AddState(sma, 'Name', 'TriggerSound2', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'Delay'},...
    'OutputActions', {'Serial1Code', 2, 'BNCState', 2});
sma = AddState(sma, 'Name', 'TriggerSound3', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'Delay'},...
    'OutputActions', {'Serial1Code', 3, 'BNCState', 2});
sma = AddState(sma, 'Name', 'Delay', ...
    'Timer', .05,...
    'StateChangeConditions', {'Tup', 'SoundOff'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'SoundOff', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {'Serial1Code', 255});