% Example state matrix: light chasing.

sma = NewStateMatrix();
                
sma = AddState(sma, 'Name', 'WaitForLick1', ...
    'Timer', .001,...
    'StateChangeConditions', {'Port1In', 'WaitForLick2'},...
    'OutputActions', {'PWM1', 255});
sma = AddState(sma, 'Name', 'WaitForLick2', ...
    'Timer', 1,...
    'StateChangeConditions', {'Port1In', 'WaitForLick3'},...
    'OutputActions', {'PWM1', 0});
sma = AddState(sma, 'Name', 'WaitForLick3', ...
    'Timer', 1,...
    'StateChangeConditions', {'Port1In', 'GiveReward'},...
    'OutputActions', {'PWM1', 255});
sma = AddState(sma, 'Name', 'GiveReward', ...
    'Timer', .5,...
    'StateChangeConditions', {'Tup', 'Final'},...
    'OutputActions', {'PWM1', 0, 'ValveState' 1});
sma = AddState(sma, 'Name', 'Final', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {});

