% Example state matrix: light chasing.

sma = NewStateMatrix();
                
sma = AddState(sma, 'Name', 'On', ...
    'Timer', .001,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {'BNCState', 1, 'PWM1', 255});
