% Example state matrix: TTL Pulse on BNC output 1

PulseDuration = .04;

sma = NewStateMatrix();

sma = AddState(sma, 'Name', 'Pulse', ...
    'Timer', PulseDuration,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {'BNCState', 1});
% sma = AddState(sma, 'Name', 'Interval', ...
%     'Timer', .036,...
%     'StateChangeConditions', {'Tup', 'Pulse2'},...
%     'OutputActions', {'BNCState', 0});
% sma = AddState(sma, 'Name', 'Pulse2', ...
%     'Timer', PulseDuration,...
%     'StateChangeConditions', {'Tup', 'exit'},...
%     'OutputActions', {'BNCState', 1});